### ISSUE TITLE
Incompatibility with Just Player Heads

### ISSUE THREAD

**Issue by TomaszewskiPatryk** [Insane96/mob-heads#7]
This mod is incompatible with [Just Player Heads](https://www.curseforge.com/minecraft/mc-mods/just-player-heads), [Just Mob Heads](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads) and probably any other mod that adds custom player heads.

When you try to break a head which isn't from this mod, it will insta-break but it won't drop any kind of item.

I'm guessing it's because the part of the code which makes sure heads drop proper item (instead of it being named "Player Head") doesn't return anything for heads outside of this mod instead of returning it's natural drop.

**Comment by Insane96** [comment]
Fixed in 1.16.5
